import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomBytes } from 'node:crypto';
import { MemoryStore, EncryptedStore } from '../../src/core/store.mjs';
import { Audit, verifyAudit } from '../../src/core/audit.mjs';
const temporary=t=>{const p=fs.mkdtempSync(path.join(os.tmpdir(),'tidal-mcp-test-'));t.after(()=>fs.rmSync(p,{recursive:true,force:true}));return p;};
test('encrypted state round-trips without exposing plaintext secrets',async t=>{
 const dir=temporary(t),key=randomBytes(32),store=new EncryptedStore(dir,key);await store.tx(s=>{s.grants.example={token:'synthetic-secret-at-rest'};});
 const text=fs.readFileSync(path.join(dir,'state.enc.json'),'utf8');assert.ok(!text.includes('synthetic-secret-at-rest'));assert.ok(!text.includes('grants'));store.close();
 const again=new EncryptedStore(dir,key);assert.equal(again.read(s=>s.grants.example.token),'synthetic-secret-at-rest');again.close();
 if(process.platform!=='win32')assert.equal(fs.statSync(path.join(dir,'state.enc.json')).mode&0o777,0o600);
});
test('encryption uses fresh nonces for identical state',async t=>{const dir=temporary(t),s=new EncryptedStore(dir,randomBytes(32));await s.tx(()=>{});const a=fs.readFileSync(s.file,'utf8');await s.tx(()=>{});assert.notEqual(fs.readFileSync(s.file,'utf8'),a);s.close();});
test('wrong encryption key fails closed and releases only its own lock',async t=>{const dir=temporary(t),s=new EncryptedStore(dir,randomBytes(32));await s.tx(()=>{});s.close();assert.throws(()=>new EncryptedStore(dir,randomBytes(32)),e=>e.code==='STORE_DECRYPTION_FAILED');assert.equal(fs.existsSync(path.join(dir,'writer.lock')),false);});
test('ciphertext tampering fails authenticated decryption',async t=>{const dir=temporary(t),key=randomBytes(32),s=new EncryptedStore(dir,key);await s.tx(()=>{});s.close();const file=path.join(dir,'state.enc.json'),e=JSON.parse(fs.readFileSync(file));const b=Buffer.from(e.ciphertext,'base64');b[0]^=1;e.ciphertext=b.toString('base64');fs.writeFileSync(file,JSON.stringify(e));assert.throws(()=>new EncryptedStore(dir,key));});
test('a second writer cannot take a live process lock',t=>{const dir=temporary(t),key=randomBytes(32),s=new EncryptedStore(dir,key);assert.throws(()=>new EncryptedStore(dir,key),e=>e.code==='STORE_LOCKED');assert.equal(fs.existsSync(s.lock),true);s.close();});
test('transactions expose copies and reject async mutation',async()=>{const s=new MemoryStore();await s.tx(x=>{x.profiles.a='one';});const copy=s.read(x=>x.profiles);copy.a='two';assert.equal(s.read(x=>x.profiles.a),'one');await assert.rejects(s.tx(async x=>{x.profiles.a='bad';}));assert.equal(s.read(x=>x.profiles.a),'one');});
test('failed persistence does not mutate committed in-memory state',async()=>{const s=new MemoryStore();s.persist=()=>{throw new Error('disk failure');};await assert.rejects(s.tx(x=>{x.profiles.bad=true;}));assert.equal(s.read(x=>x.profiles.bad),undefined);});
test('audit logs only allowlisted metadata and validates its hash chain',t=>{const dir=temporary(t),file=path.join(dir,'audit.jsonl'),a=new Audit(file);a.write({event:'tool.invoke',tool:'tidal_get',arguments:{query:'private taste'},token:'synthetic-no-log'});a.write({event:'http.request',route:'/mcp',status:200});const text=fs.readFileSync(file,'utf8');assert.ok(!text.includes('private taste'));assert.ok(!text.includes('synthetic-no-log'));assert.equal(verifyAudit(text).sequence,2);assert.equal(verifyAudit(text).valid,true);const again=new Audit(file);again.write({event:'restart'});assert.equal(verifyAudit(fs.readFileSync(file,'utf8')).sequence,3);});
test('audit content tampering is detected on startup',t=>{const dir=temporary(t),file=path.join(dir,'audit.jsonl'),a=new Audit(file);a.write({event:'tool.invoke',status:'ok'});const text=fs.readFileSync(file,'utf8').replace('"ok"','"bad"');assert.equal(verifyAudit(text).valid,false);fs.writeFileSync(file,text);assert.throws(()=>new Audit(file));});
